export {default as Home} from './home/Home'
export {default as About} from './about/About'
export {default as Commit} from './about/Commit'
export {default as Track} from './track/Track'
export {default as BangGia} from './track/BangGia'
export {default as VanDon} from './track/VanDon'

export {default as Adivce} from './advice/Advice'
export {default as Contact} from './advice/contact/Contact.advice'
export {default as SignUpAdvice} from './advice/signUpForAdvise/SignUp.advice'
export {default as PageNotFound} from './PageNotFound'

export {default as Layer} from './Layer'
export {default as LayerStorekeeper} from './storekeeper/LayerStorekeeper'
export {default as ProductsManager} from './storekeeper/ProductsManager'
export {default as Inventory} from './storekeeper/Inventory'